//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчетЛПА
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ознакомление
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Дата_время { get; set; }
        public int id_сотрудника { get; set; }
        public int id_ЛПА { get; set; }
    
        public virtual ЛПА ЛПА { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
